using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace NLEditor
{
    public static class HotkeyConfig
    {
        public static Keys HotkeyCreateNewLevel;
        public static Keys HotkeyLoadLevel;
        public static Keys HotkeySaveLevel;
        public static Keys HotkeySaveLevelAs;
        public static Keys HotkeyPlaytestLevel;
        public static Keys HotkeyValidateLevel;
        public static Keys HotkeyToggleClearPhysics;
        public static Keys HotkeyToggleTerrain;
        public static Keys HotkeyToggleObjects;
        public static Keys HotkeyToggleTriggerAreas;
        public static Keys HotkeyToggleScreenStart;
        public static Keys HotkeyToggleBackground;
        public static Keys HotkeyToggleSnapToGrid;
        public static Keys HotkeyOpenSettings;
        public static Keys HotkeyOpenHotkeyConfig;
        public static Keys HotkeyOpenAboutSLX;
        public static Keys HotkeySelectPieces;
        public static Keys HotkeyDragToScroll;
        public static Keys HotkeyRemovePiecesAtCursor;
        public static Keys HotkeyAddRemoveSinglePiece;
        public static Keys HotkeySelectPiecesBelow;
        public static Keys HotkeyZoomIn;
        public static Keys HotkeyZoomOut;
        public static Keys HotkeyScrollHorizontally;
        public static Keys HotkeyScrollVertically;
        public static Keys HotkeyMoveScreenStart;
        public static Keys HotkeyShowPreviousPiece;
        public static Keys HotkeyShowNextPiece;
        public static Keys HotkeyShowPreviousGroup;
        public static Keys HotkeyShowNextGroup;
        public static Keys HotkeyShowPreviousStyle;
        public static Keys HotkeyShowNextStyle;
        public static Keys HotkeySwitchBrowser;
        public static Keys HotkeyAddPiece1;
        public static Keys HotkeyAddPiece2;
        public static Keys HotkeyAddPiece3;
        public static Keys HotkeyAddPiece4;
        public static Keys HotkeyAddPiece5;
        public static Keys HotkeyAddPiece6;
        public static Keys HotkeyAddPiece7;
        public static Keys HotkeyAddPiece8;
        public static Keys HotkeyAddPiece9;
        public static Keys HotkeyAddPiece10;
        public static Keys HotkeyAddPiece11;
        public static Keys HotkeyAddPiece12;
        public static Keys HotkeyAddPiece13;
        public static Keys HotkeyUndo;
        public static Keys HotkeyRedo;
        public static Keys HotkeyCut;
        public static Keys HotkeyCopy;
        public static Keys HotkeyPaste;
        public static Keys HotkeyDuplicate;
        public static Keys HotkeyDelete;
        public static Keys HotkeyMoveUp;
        public static Keys HotkeyMoveDown;
        public static Keys HotkeyMoveLeft;
        public static Keys HotkeyMoveRight;
        public static Keys HotkeyMove8Up;
        public static Keys HotkeyMove8Down;
        public static Keys HotkeyMove8Left;
        public static Keys HotkeyMove8Right;
        public static Keys HotkeyCustomMove;
        public static Keys HotkeyDragHorizontally;
        public static Keys HotkeyDragVertically;
        public static Keys HotkeyRotate;
        public static Keys HotkeyFlip;
        public static Keys HotkeyInvert;
        public static Keys HotkeyGroup;
        public static Keys HotkeyUngroup;
        public static Keys HotkeyErase;
        public static Keys HotkeyNoOverwrite;
        public static Keys HotkeyOnlyOnTerrain;
        public static Keys HotkeyAllowOneWay;
        public static Keys HotkeyDrawLast;
        public static Keys HotkeyDrawSooner;
        public static Keys HotkeyDrawLater;
        public static Keys HotkeyDrawFirst;
        public static Keys HotkeyCloseWindow;
        public static Keys HotkeyCloseEditor;
    }
}
