//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NLEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowAboutSLXWindowAtStartup {
            get {
                return ((bool)(this["ShowAboutSLXWindowAtStartup"]));
            }
            set {
                this["ShowAboutSLXWindowAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LevelArrangerIsOpen {
            get {
                return ((bool)(this["LevelArrangerIsOpen"]));
            }
            set {
                this["LevelArrangerIsOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllTabsAreExpanded {
            get {
                return ((bool)(this["AllTabsAreExpanded"]));
            }
            set {
                this["AllTabsAreExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("960, 400")]
        public global::System.Drawing.Size LevelArrangerSize {
            get {
                return ((global::System.Drawing.Size)(this["LevelArrangerSize"]));
            }
            set {
                this["LevelArrangerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("180, 40")]
        public global::System.Drawing.Point LevelArrangerLocation {
            get {
                return ((global::System.Drawing.Point)(this["LevelArrangerLocation"]));
            }
            set {
                this["LevelArrangerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LevelArrangerIsMaximized {
            get {
                return ((bool)(this["LevelArrangerIsMaximized"]));
            }
            set {
                this["LevelArrangerIsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ErasersAreHighlighted {
            get {
                return ((bool)(this["ErasersAreHighlighted"]));
            }
            set {
                this["ErasersAreHighlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GroupsAreHighlighted {
            get {
                return ((bool)(this["GroupsAreHighlighted"]));
            }
            set {
                this["GroupsAreHighlighted"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000, 148")]
        public global::System.Drawing.Size PieceBrowserSize {
            get {
                return ((global::System.Drawing.Size)(this["PieceBrowserSize"]));
            }
            set {
                this["PieceBrowserSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40, 560")]
        public global::System.Drawing.Point PieceBrowserLocation {
            get {
                return ((global::System.Drawing.Point)(this["PieceBrowserLocation"]));
            }
            set {
                this["PieceBrowserLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PieceBrowserIsMaximized {
            get {
                return ((bool)(this["PieceBrowserIsMaximized"]));
            }
            set {
                this["PieceBrowserIsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PieceBrowserIsOpen {
            get {
                return ((bool)(this["PieceBrowserIsOpen"]));
            }
            set {
                this["PieceBrowserIsOpen"] = value;
            }
        }
    }
}
